<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>52f053bb-48b0-4b0c-bd07-fe7622751ea8</elementGuidId>
    <imagePath></imagePath>
    <name>button_assign-to-me-trigger</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[8]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#assign-to-me-trigger</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'assign-to-me-trigger') and equals(@type,'button') and equals(@text,'Assign to me')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Assign to me"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>assign-to-me-trigger</value>
        <webElementGuid>24963d7b-2284-4c88-b43b-03522c227138</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Assign to me</value>
        <webElementGuid>24963d7b-2284-4c88-b43b-03522c227138</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>24963d7b-2284-4c88-b43b-03522c227138</webElementGuid>
    </webElementProperties>
</WebElementEntity>