<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0aedc6b3-8791-4181-832e-8d941b801301</elementGuidId>
    <imagePath></imagePath>
    <name>rich_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[9]/div[1]/rich-editor[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#mce_0</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#mce_0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>